# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ UI ]
  pull_request:
    branches: [ UI ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install  qiniu
      
    - name: cddir
      run: |
        # stop the build if there are Python syntax errors or undefined names
        cd utils
       
    - name: push ui qiniu
      run: |
        python qiniu_upload.py ${{ secrets.QINIU_AK }}  ${{ secrets.QINIU_SK }}
        
